In [5]:
#1.Create a null vector of size 10 but the fifth value which is 1
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
#2.Create a vector with values ranging from 10 to 49
Z = 10 + np.arange(40)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#3.Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#4.Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [14]:
#5.Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)

[[0.62187011 0.66043269 0.44434661 0.68811036 0.62763692 0.23087427
  0.46294207 0.35615099 0.96259393 0.38048915]
 [0.02198126 0.45044239 0.23938135 0.66054857 0.62398636 0.35739123
  0.73371278 0.60311268 0.21445178 0.86980838]
 [0.39075692 0.5632591  0.61793952 0.40553094 0.89764703 0.00112738
  0.80883097 0.86730084 0.66737527 0.87517239]
 [0.88931523 0.73521151 0.43802803 0.36699477 0.4024173  0.550003
  0.50428676 0.96715771 0.691175   0.08634399]
 [0.98544436 0.83398994 0.91360386 0.17099218 0.14859956 0.61118507
  0.02819229 0.03271446 0.09537052 0.12953976]
 [0.23434016 0.26792203 0.30507682 0.9084493  0.58124969 0.96976021
  0.18480124 0.56834395 0.6504323  0.79823219]
 [0.6587624  0.3388718  0.29355459 0.06126419 0.19889324 0.64146875
  0.69689079 0.14421605 0.77600187 0.12641312]
 [0.19563292 0.87172151 0.07067379 0.78409635 0.14540514 0.75925677
  0.16995561 0.12973303 0.81456255 0.07370034]
 [0.79347387 0.13462205 0.51371834 0.99486204 0.01502266 0.62020169
  0.84031214 0

In [15]:
#6.Create a random vector of size 30 and find the mean value.
Z = np.random.random(100)
Z.sort()
m = Z.mean()
print(m)

0.5010030834402402
